# Generated by Django 5.1.7 on 2025-04-01 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='imports/')),
                ('semestre', models.IntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')])),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('erreur', 'Erreur')], default='en_cours', max_length=10)),
                ('erreur_message', models.TextField(blank=True, null=True)),
                ('annee_scolaire', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['-date_import'],
            },
        ),
        migrations.CreateModel(
            name='MoyenneEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_eleve', models.CharField(max_length=100)),
                ('prenom_eleve', models.CharField(blank=True, max_length=100, null=True)),
                ('moyenne_generale', models.FloatField()),
                ('rang', models.IntegerField(blank=True, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes', to='core.classe')),
                ('import_fichier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes', to='core.importfichier')),
            ],
            options={
                'ordering': ['-moyenne_generale'],
            },
        ),
        migrations.CreateModel(
            name='MoyenneDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_discipline', models.CharField(max_length=100)),
                ('moyenne', models.FloatField()),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='core.moyenneeleve')),
            ],
        ),
    ]
