# Generated by Django 5.1.7 on 2025-04-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_donneesdetailleeseleves_donneesmoyenneseleves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moyenneeleve',
            name='moyenne_generale',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
