# Generated by Django 5.1.7 on 2025-04-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_moyenneeleve_moyenne_generale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moyenneeleve',
            options={'ordering': ['-moyenne_generale'], 'verbose_name': 'Moyenne Élève', 'verbose_name_plural': 'Moyennes Élèves'},
        ),
    ]
