# Generated by Django 5.1.7 on 2025-04-02 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_moyenneeleve_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donneesmoyenneseleves',
            old_name='classe',
            new_name='classe_texte',
        ),
        migrations.AddField(
            model_name='donneesmoyenneseleves',
            name='classe_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donnees_moyennes', to='core.classe'),
        ),
        migrations.AddField(
            model_name='donneesmoyenneseleves',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donnees_moyennes', to='core.niveau'),
        ),
    ]
