# Generated by Django 5.1.7 on 2025-04-02 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_classe_donneesmoyenneseleves_classe_texte_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donneesdetailleeseleves',
            options={},
        ),
    ]
