# Generated by Django 5.1.7 on 2025-04-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_donneesdetailleeseleves_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfichier',
            name='donnees_supplementaires',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
