# Generated by Django 5.1.7 on 2025-04-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_importfichier_donnees_supplementaires'),
    ]

    operations = [
        migrations.AddField(
            model_name='donneesdetailleeseleves',
            name='sexe',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
